apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: fibs-service
  namespace: jduimovich-dev
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: fib
  sessionAffinity: None
  type: ClusterIP
